name: User Onboarding Test

on:
  pull_request_target: # Need access to secrets
    branches: [main]
  push:
    branches: [main]

jobs:
  test-onboarding:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Verify prerequisites
        run: |
          echo "Docker version:"
          docker --version
          echo "Docker Compose version:"
          docker compose version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run start script
        run: |
          chmod +x start.sh
          { echo "y"; echo "${{ secrets.OPENAI_API_KEY }}"; echo "n"; echo "y"; } | ./start.sh

      - name: Run backend-specific health checks
        run: |
          docker exec -e AIRWEAVE_TEST_ENV=onboarding airweave-backend pytest tests/e2e/smoke/test_basic_health.py -v

      - name: Run frontend health checks
        run: |
          echo "Checking frontend accessibility..."
          FRONTEND_URL="http://localhost:8080"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" $FRONTEND_URL)

          if [ "$HTTP_STATUS" == "200" ]; then
            echo "Frontend accessibility test passed!"
          else
            echo "Frontend test failed: HTTP status $HTTP_STATUS"
            exit 1
          fi

      - name: Run user onboarding test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: |
          docker exec -e OPENAI_API_KEY=${OPENAI_API_KEY} -e STRIPE_API_KEY=${STRIPE_API_KEY} -e AIRWEAVE_TEST_ENV=onboarding airweave-backend pytest tests/e2e/smoke/test_user_onboarding.py -sv
