name: Backend Tests

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Run on feature instead of main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1

      - name: Install dependencies
        run: |
          cd backend
          poetry install

      - name: Run all tests
        env:
          AIRWEAVE_TEST_ENV: test
          ENCRYPTION_KEY: "SpgLrrEEgJ/7QdhSMSvagL1juEY5eoyCG0tZN7OSQV0=" # This is just a dummy key
          FIRST_SUPERUSER: admin@airweave.ai
          FIRST_SUPERUSER_PASSWORD: airweave1234!
          POSTGRES_USER: airweave
          POSTGRES_DB: airweave
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: airweave1234!
          POSTGRES_PORT: 5432
          PROJECT_NAME: airweave
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }} # Used for e2e sync tests

        run: |
          cd backend
          poetry run pytest tests/ --ignore=tests/e2e/smoke/test_user_onboarding.py --cov=airweave --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml
          fail_ci_if_error: false
          verbose: true
